#ifndef ESTADOS_H
#define ESTADOS_H

typedef enum {
    ESTADO_AGUARDANDO_INICIO,
    ESTADO_REPRODUZINDO_SEQUENCIA,
    ESTADO_AGUARDANDO_JOGADA,
    ESTADO_PROCESSANDO_JOGADA,
    ESTADO_AGUARDANDO_PROXIMA,
    ESTADO_VITORIA,
    ESTADO_DERROTA
} EstadoJogo;

#endif